-- 코드를 입력하세요
# SELECT I.REST_ID, I.REST_NAME, I.FOOD_TYPE, I.FAVORITES, I.ADDRESS, ROUND(AVG(R.REVIEW_SCORE),2) AS SCORE
# FROM REST_INFO AS I
# INNER JOIN REST_REVIEW AS R
# ON I.REST_ID = R.REST_ID
# WHERE I.ADDRESS LIKE '서울%'
# GROUP BY I.REST_ID
# ORDER BY SCORE DESC, I.VIEWS ASC;

# SELECT R.REST_ID, I.REST_NAME, I.FOOD_TYPE, I.FAVORITES, I.ADDRESS, ROUND(AVG(R.REVIEW_SCORE),2) AS SCORE
# FROM REST_INFO  I
# INNER JOIN REST_REVIEW  R ON I.REST_ID = R.REST_ID
# GROUP BY I.REST_ID
# HAVING I.ADDRESS LIKE '서울%'
# ORDER BY SCORE DESC, I.FAVORITES ASC;

SELECT A.REST_ID, B.REST_NAME, B.FOOD_TYPE, B.FAVORITES, B.ADDRESS, ROUND(AVG(A.REVIEW_SCORE),2) AS SCORE
FROM REST_REVIEW A
JOIN REST_INFO B ON A.REST_ID = B.REST_ID
GROUP BY A.REST_ID
HAVING B.ADDRESS LIKE '서울%'
ORDER BY SCORE DESC, B.FAVORITES DESC