-- 코드를 입력하세요
# SELECT YEAR(A.SALES_DATE) AS YEAR, 
#        MONTH(A.SALES_DATE) AS MONTH,
#        B.GENDER AS GENDER, 
#        COUNT(*) AS USERES
# FROM ONLINE_SALE AS A
#      JOIN (SELECT * FROM USER_INFO WHERE GENDER) AS B
#      ON A.USER_ID = B.USER_ID
# GROUP BY YEAR, MONTH, GENDER
# HAVING GENDER != ' '
# ORDER BY YEAR, MONTH, GENDER


SELECT
    DATE_FORMAT(S.SALES_DATE, '%Y') AS YEAR,
    DATE_FORMAT(S.SALES_DATE, '%m') AS MONTH,
    I.GENDER,
    COUNT(DISTINCT S.USER_ID) AS USERS
FROM USER_INFO I
JOIN ONLINE_SALE S ON I.USER_ID = S.USER_ID
WHERE I.GENDER IS NOT NULL
GROUP BY YEAR, MONTH, I.GENDER
ORDER BY YEAR, MONTH, I.GENDER;