# -- 코드를 입력하세요
SELECT DATE_FORMAT(A.SALES_DATE, '%Y') AS YEAR, 
       DATE_FORMAT(A.SALES_DATE, '%m') AS MONTH,
       GENDER, 
       COUNT(DISTINCT A.USER_ID) AS USERES
FROM ONLINE_SALE AS A
     JOIN USER_INFO AS B
     ON A.USER_ID = B.USER_ID
GROUP BY YEAR, MONTH, B.GENDER
HAVING GENDER IS NOT NULL
ORDER BY YEAR, MONTH, B.GENDER


# SELECT
#     DATE_FORMAT(S.SALES_DATE, '%Y') AS YEAR,
#     DATE_FORMAT(S.SALES_DATE, '%m') AS MONTH,
#     I.GENDER,
#     COUNT(DISTINCT S.USER_ID) AS USERS
# FROM USER_INFO I
# JOIN ONLINE_SALE S ON I.USER_ID = S.USER_ID
# WHERE I.GENDER IS NOT NULL
# GROUP BY YEAR, MONTH, I.GENDER
# ORDER BY YEAR, MONTH, I.GENDER;