-- 코드를 입력하세요
SELECT DATE_FORMAT(O.SALES_DATE,'%Y') AS YEAR,
       DATE_FORMAT(O.SALES_DATE,'%m') AS MONTH,
       COUNT(DISTINCT(U.USER_ID)) AS PURCHASED_USERS,
       ROUND(COUNT(DISTINCT(U.USER_ID)) / (SELECT COUNT(*)
                                            FROM USER_INFO
                                            WHERE DATE_FORMAT(JOINED,'%Y') = 2021),1) AS PURCHASED_RATIO

FROM ONLINE_SALE AS O
JOIN USER_INFO AS U
ON O.USER_ID = U.USER_ID
WHERE DATE_FORMAT(U.JOINED,'%Y') = 2021
GROUP BY DATE_FORMAT(O.SALES_DATE,'%Y'), DATE_FORMAT(O.SALES_DATE,'%m')
ORDER BY YEAR, MONTH


# SELECT  YEAR(A.SALES_DATE) AS YEAR
#         , MONTH(A.SALES_DATE) AS MONTH
#         , COUNT(DISTINCT(B.USER_ID)) AS PUCHASED_USERS
#         , ROUND(COUNT(DISTINCT B.USER_ID)/(SELECT COUNT(USER_ID) FROM USER_INFO WHERE YEAR(JOINED)='2021'), 1)
#     AS PURCHASED_RATIO
#   FROM  ONLINE_SALE AS A
#   LEFT
#   JOIN  USER_INFO AS B
#     ON  A.USER_ID = B.USER_ID
#  WHERE  YEAR(B.JOINED)='2021'
#  GROUP
#     BY  YEAR(A.SALES_DATE)
#         , MONTH(A.SALES_DATE)
#  ORDER
#     BY  YEAR ASC
#         , MONTH ASC