SELECT ITEM_ID, ITEM_NAME, RARITY
FROM ITEM_INFO
WHERE ITEM_ID IN (
    SELECT A.ITEM_ID
    FROM ITEM_TREE AS A
    WHERE PARENT_ITEM_ID IN (
        SELECT ITEM_ID 
        FROM ITEM_INFO AS C
        WHERE RARITY = 'RARE'))
ORDER BY ITEM_ID DESC
