-- 코드를 작성해주세요
SELECT REA.ID, REA.GENOTYPE, TEMP.GENOTYPE AS PARENT_GENOTYPE
FROM (  SELECT PA.ID, CH.GENOTYPE
        FROM ECOLI_DATA AS PA
        LEFT JOIN ECOLI_DATA AS CH
        ON PA.PARENT_ID = CH.ID) AS TEMP
LEFT JOIN ECOLI_DATA AS REA
ON TEMP.ID = REA.ID
WHERE TEMP.GENOTYPE & REA.GENOTYPE = TEMP.GENOTYPE